### ISSUE TITLE
 UnboundLocalError if batch is finalized before carrier is entered

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/iromlab#21]
Edge case:

    Exception in thread Thread-3:
    Traceback (most recent call last):
      File "C:\python27\lib\threading.py", line 810, in __bootstrap_inner
        self.run()
      File "C:\python27\lib\threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "f:\johan\pythonCode\iromlab\iromlab\cdworker.py", line 399, in cdWorker
        if success == True and endOfBatchFlag == False:
    UnboundLocalError: local variable 'success' referenced before assignment

**Comment by bitsgalore** [comment]
Fixed: <https://github.com/KBNLresearch/iromlab/commit/4f77dda8faa0f78ad811dc50cf7e7b767ede2da1>
