### ISSUE TITLE
Py 3:  join raises TypeError (expected str instance, bytes found)

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/iromlab#24]
Exception in thread Thread-3:
    Traceback (most recent call last):
      File "c:\python36\lib\threading.py", line 916, in _bootstrap_inner
        self.run()
      File "c:\python36\lib\threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "c:\python36\lib\site-packages\iromlab\cdworker.py", line 360, in cdWorke
    r
        logging.info(''.join(['prebatch command output: ',resultPrebatch['log'].stri
    p()]))
    TypeError: sequence item 1: expected str instance, bytes found

**Comment by bitsgalore** [comment]
Fixed <https://github.com/KBNLresearch/iromlab/commit/24858a15ed0a17d8325b524d6be520e686848b71>
