### ISSUE TITLE
Py3: AttributeError: module 'urllib' has no attribute 'quote_plus' 

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/iromlab#25]
Traceback (most recent call last):
      File "c:\python36\lib\tkinter\__init__.py", line 1699, in __call__
        return self.func(*args)
      File "f:\johan\pythonCode\iromlab\iromlab\iromlab.py", line 176, in on_submit
        response = sru.search(sruSearchString,"GGC")
      File "f:\johan\pythonCode\iromlab\iromlab\kbapi\sru.py", line 267, in search
        self.query = urllib.quote_plus(query)
    AttributeError: module 'urllib' has no attribute 'quote_plus'

**Comment by bitsgalore** [comment]
Fixed: <https://github.com/KBNLresearch/iromlab/commit/587b996033a08646e6e172d46b5582fe9759e0b4>
