### ISSUE TITLE
AtributeError if entered PPN doesn't exist

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/iromlab#27]
Happens both in Py 2.7 and 3.6:

    Traceback (most recent call last):
      File "c:\python36\lib\tkinter\__init__.py", line 1699, in __call__
        return self.func(*args)
      File "f:\johan\pythonCode\iromlab\iromlab\iromlab.py", line 177, in on_submit
        noGGCRecords = response.sru.nr_of_records
    AttributeError: 'bool' object has no attribute 'sru'

Expected behaviour: messagebox!

**Comment by bitsgalore** [comment]
Fixed: <https://github.com/KBNLresearch/iromlab/commit/b49111a6ef029657bf049933a10eda38113f220c>
