### ISSUE TITLE
x_wmi_uninitialised_thread

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/iromlab#5]
Sometimes this happens while loading a disc:

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
        self.run()
      File "C:\Python27\lib\threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "f:/johan/pythoncode/iromlab/iromlab/iromlab.py", line 816, in cdWorker
        processDisc(carrierData)
      File "f:/johan/pythoncode/iromlab/iromlab/iromlab.py", line 534, in processDis
    c
        foundDrive, discLoaded = mediumLoaded(config.cdDriveLetter + ":")
      File "f:/johan/pythoncode/iromlab/iromlab/iromlab.py", line 297, in mediumLoad
    ed
        c = wmi.WMI()
      File "C:\Python27\lib\site-packages\wmi.py", line 1293, in connect
        raise x_wmi_uninitialised_thread ("WMI returned a syntax error: you're proba
    bly running inside a thread without first calling pythoncom.CoInitialize[Ex]")
    x_wmi_uninitialised_thread: <x_wmi: WMI returned a syntax error: you're probably
     running inside a thread without first calling pythoncom.CoInitialize[Ex] (no un
    derlying exception)>

Possible solution here: 

<http://stackoverflow.com/questions/14428707/python-function-is-unable-to-run-in-new-thread>

Note:  so far this has only happened after opening an existing batch (and never after creating a new one). Could be a coincidence ...

**Comment by bitsgalore** [comment]
Fixed with <https://github.com/KBNLresearch/iromlab/commit/ab06ea5ec2b6cf84a91fd957494d3393cc280c6d>
