### ISSUE TITLE
Iromlab doesn't exit if Finalize button is pressed after last disc has been processed

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/iromlab#50]

**Comment by bitsgalore** [comment]
Possibly related/same issue: while running iromlab from console this happened after pressing Finalize:

    Exception in Tkinter callback
    Traceback (most recent call last):
      File "C:\Python36\lib\tkinter\__init__.py", line 1699, in __call__
        return self.func(*args)
      File "C:\Python36\lib\tkinter\__init__.py", line 745, in callit
        func(*args)
      File "F:\johan\pythonCode\iromlab\iromlab\iromlab.pyw", line 348, in append
        self.text.configure(state='normal')
      File "C:\Python36\lib\tkinter\__init__.py", line 1479, in configure
        return self._configure('configure', cnf, kw)
      File "C:\Python36\lib\tkinter\__init__.py", line 1470, in _configure
        self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
    KeyboardInterrupt

**Comment by bitsgalore** [comment]
Added 2-second delay before KeyboardInterrupt <https://github.com/KBNLresearch/iromlab/commit/e1e30f6380febf229a9153eaf9a22d8006b1e497>
