### ISSUE TITLE
Exception if no disc is loaded

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/iromlab#87]
Steps to reproduce:

1. Run Iromlab with startOnFinalise is True
2. Enter PPNs, volume numbers of a couple of carriers
3. Only insert 1 actual disc (!)
4. Hit Finalise

Result: after 1st disc has been processed, the following exception occurs:

    Exception in thread Thread-3:
    Traceback (most recent call last):
      File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
        self.run()
      File "C:\Python36\lib\threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "F:\johan\pythonCode\iromlab\iromlab\cdworker.py", line 539, in cdWorker
        success = processDisc(carrierData)
      File "F:\johan\pythonCode\iromlab\iromlab\cdworker.py", line 367, in processDi
    sc
        str(carrierInfo['mixedMode']),
    KeyError: 'mixedMode'

Log entry:

    2019-05-07 15:31:01,217 - INFO - ### Job identifier: e6566eae-70cb-11e9-b5d4-7446a0b42b9a
    2019-05-07 15:31:01,217 - INFO - PPN: 18594650X
    2019-05-07 15:31:01,218 - INFO - Title: Thea Beckman
    2019-05-07 15:31:01,218 - INFO - Volume number: 2
    2019-05-07 15:31:01,218 - INFO - disc directory: e:\nimbieTest\kb-d5911868-70cb-11e9-8ca4-7446a0b42b9a\e6566eae-70cb-11e9-b5d4-7446a0b42b9a
    2019-05-07 15:31:01,219 - INFO - *** Loading disc ***
    2019-05-07 15:31:03,911 - INFO - load command: C:\Program Files\dBpoweramp\BatchRipper\Loaders\Nimbie\Load\Load.exe --drive=H --rejectifnodisc --logfile=C:\Temp\H4lsAOK023P0.log --passerrorsback=C:\Temp\VoGbN62FwsG5.err
    2019-05-07 15:31:03,912 - INFO - load command output: Init Nimbie: Connecting to Nimbie: Close Nimbie: Closed
    2019-05-07 15:31:33,108 - ERROR - no disc loaded
    2019-05-07 15:31:33,108 - INFO - reject command: C:\Program Files\dBpoweramp\BatchRipper\Loaders\Nimbie\Reject\Reject.exe --drive=H --logfile=C:\Temp\eoB0tEitJMYM.log --passerrorsback=C:\Temp\GSTjlfV8PYPb.err
    2019-05-07 15:31:33,108 - INFO - reject command output: Init Nimbie: Connecting to Nimbie: Close Nimbie: Closed

**Comment by bitsgalore** [comment]
Fixed: <https://github.com/KBNLresearch/iromlab/commit/2f3fbd521ceaded449cf6817b3308a1909c15f3a>
